#!/usr/bin/env bash
# This script prints:
#     * "holbertonschool file exists" when file exists.
#     * "holbertonschool file does not exist" when file doesn't exist.
#     * "holbertonschool file is not empty" when file not empty.
#     * "holbertonschool file is empty" when file is empty.
#     * "holbertonschool file is a regular file" when file is not a directory
#         or device file.

file="holbertonschool"

if [ -e $file ]
then
    echo "$file file exists"
    if [ -s $file ]
    then
	echo "$file file is not empty"
    else
	echo "$file file is empty"
    fi

    if [ -f $file ]
    then
	echo "$file is a regular file"
    fi
else
    echo "$file file does not exist"
fi
